[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "5hGhaKA4fbHGX2qkU6gPv8QnMSRE2jUJtNnaG5Dk65ZQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
